### ISSUE TITLE
atom's deprecation

### ISSUE THREAD

**Issue by ghost** [ryanpcmcquen/atom-plain#4]
![capture](https://cloud.githubusercontent.com/assets/17445894/21960212/1b70438e-daf3-11e6-9087-1ecb460edead.JPG)
and using moment wanted to say huge thanks for the theme, alone which i like, thank you

**Comment by ryanpcmcquen** [comment]
Thanks for the ping! I will get it fixed up soon.

**Comment by ghost** [comment]
thank you, appreciate your work

**Comment by ryanpcmcquen** [comment]
Should be live any minute!

**Comment by ghost** [comment]
)
